create table users
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    status     VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    user_role varchar(20) not null
);

create table files
(
    id        int generated by default as identity primary key,
    location varchar(255),
    status     VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
);

create table events
(
    id      int generated by default as identity primary key,
    user_id int,
    file_id int,
    status     VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    constraint fk_events_on_users foreign key (user_id) references users (id),
    constraint fk_events_on_files foreign key (file_id) references files (id)
);